image: Visual Studio 2019

init:
- ps: Get-Path
- ps: $env:path
- ps: |
    if (Test-Path 'C:\Strawberry') {
      Remove-Path 'C:\Strawberry\c\bin'
      Remove-Path 'C:\Strawberry\perl\site\bin'
    }
- ps: Get-Path
- ps: $env:path
